version: '3'
services:
  whale:
    build: .
    ports:
      - "8080:8080"
    environment:
      - SPRING_FLYWAY_URL=jdbc:mysql://mysql/
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql/mobydick
    depends_on:
      - mysql
    restart: "on-failure"
  mysql:
    image: mysql:5.7
    environment:
      - MYSQL_ROOT_PASSWORD=ahad123
      - MYSQL_USER=whale
      - MYSQL_PASSWORD=blue-whale
      - MYSQL_DATABASE=mobydick
    volumes:
      - ./data:/var/lib/mysql
